USE Performance_review;

CREATE TRIGGER TR_AgeCalculation
BEFORE INSERT ON User 
FOR EACH ROW 
	SET NEW.Age = TIMESTAMPDIFF(YEAR,NEW.Birthday,CURDATE());

DELIMITER $$
CREATE TRIGGER TR_AgeValidation 
BEFORE INSERT ON User 
FOR EACH ROW 
BEGIN
	IF 18 >= NEW.Age OR NEW.Age >= 120 THEN 
		SET NEW.Age = 0;
	END IF;
END;$$
